name: reminest
description: "A secure mental health journaling app with vault functionality"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0

  # Encryption & Security
  pointycastle: ^3.7.3
  crypto: ^3.0.3

  # Storage & Files
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.8.3
  file_picker: ^6.1.1

  # UI & Navigation
  url_launcher: ^6.2.1
  logger: ^2.6.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
