name: Reminest
description: "Reminest - A secure, encrypted personal journal vault."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  sqlite3: ^2.4.0
  ffi: ^2.1.0
  encrypt: ^5.0.3
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/Reminest.png
    - lib/assets/icons/Reminest.ico
