name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, inital ]
  pull_request:
    branches: [ main, develop, inital ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze code
      run: flutter analyze

    - name: Run tests
      run: flutter test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        name: reminest-coverage
        fail_ci_if_error: false

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: reminest-android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build-web:
    name: Build Web App
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web --release

    - name: Upload Web artifact
      uses: actions/upload-artifact@v4
      with:
        name: reminest-web-app
        path: build/web/

  build-windows:
    name: Build Windows App
    runs-on: windows-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows --release

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: reminest-windows-app
        path: build/windows/x64/runner/Release/

  build-linux:
    name: Build Linux App
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'

    - name: Install Linux dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev

    - name: Get dependencies
      run: flutter pub get

    - name: Build Linux
      run: flutter build linux --release

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: reminest-linux-app
        path: build/linux/x64/release/bundle/

  build-macos:
    name: Build macOS App
    runs-on: macos-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build macOS
      run: flutter build macos --release

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: reminest-macos-app
        path: build/macos/Build/Products/Release/

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build iOS (no signing)
      run: flutter build ios --release --no-codesign

    - name: Upload iOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: reminest-ios-app
        path: build/ios/iphoneos/

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-android, build-web, build-windows, build-linux, build-macos, build-ios]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Reminest v${{ github.run_number }}
        body: |
          Cross-platform build of Reminest Mental Health Vault
          
          ## Platforms Available:
          - 🤖 Android APK
          - 🌐 Web App
          - 🪟 Windows App
          - 🐧 Linux App
          - 🍎 macOS App
          - 📱 iOS App
          
          ## Changes in this release:
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
